name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo GitHub Actions!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SetupNode
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # - run: npm ci
      - name: Definir una variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - run: npm test
